version: '3'

services:
  accounts-app:
    image: take-home/accounts-app-docker:latest
    container_name: accounts
    environment:
     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka:8761/eureka/
     - KAFKA_BOOTSTRAPSERVERS= kafka:9092
    depends_on:
     - eureka
  orderdetail-app:
    image: take-home/orderdetail-app-docker:latest
    container_name: orderdetails
    environment:
     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka:8761/eureka/
     - KAFKA_BOOTSTRAPSERVERS= kafka:9092
    depends_on:
     - eureka
  eureka:
    image: take-home/eurekaserver-docker:latest
    container_name: eureka
    ports:
     - 8761:8761
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka-l
    ports:
     - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
